name: check-code
run-name: Checking ${{ github.actor }} code
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Linting
        run: yarn lint
      
      - name: Test
        run: yarn test